### ISSUE TITLE
Makefile support on macOS

### ISSUE THREAD

**Issue by GeraltShi** [WangyuHello/Wonton#3]
Compiling automation by using GNUMake.
On windows maybe try GNUWin32/Cygwin/Mingw.

**Comment by GeraltShi** [comment]
By using Makefile we can hide the patch stuff in fast deployment.
The text insertion can be carried out by a shell script, which is to be called later in Makefile.
(But this is not an urgent feature to support.)

**Comment by WangyuHello** [comment]
使用对C#友好的Cake自动构建系统，支持macOS
