### ISSUE TITLE
Minor issue: The icon has a bar at the bottom after clicking the play button, but it does not change back after stopping.

### ISSUE THREAD

**Issue by GeraltShi** [WangyuHello/Wonton#9]
As title.

<img width="952" alt="Snipaste_2020-02-13_14-43-15" src="https://user-images.githubusercontent.com/25215492/74408398-4689e500-4e6f-11ea-889f-d50de7133484.png">

**Comment by WangyuHello** [comment]
Dock图标上的bar是进度条, v1.0.5版本已经修复play按钮问题
